# Generated by Django 4.1.3 on 2022-11-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_employee_annual_salary_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
